services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #   restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # deploy-repo 기준 경로
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    image: rlarltn/cosy_frontend:latest
    container_name: frontend
    ports:
      - "3000:3000" # 로컬 개발 시 브라우저에서 접근 가능
    expose:
      - "3000" # Nginx 등 다른 컨테이너에서 내부 접근 허용
    depends_on:
      - backend
    env_file:
      - ./.env
    restart: always

  backend:
    image: rlarltn/cosy_backend:latest # Docker Hub의 최신 이미지 사용
    container_name: backend
    ports:
      - "4000:4000" # 로컬 개발 시 브라우저에서 접근 가능
    expose:
      - "4000" # Nginx 등 다른 컨테이너에서 내부 접근 허용
    env_file:
      - ./.env
    restart: always
networks:
  default:
    driver: bridge
