services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #   restart: always

  backend:
    image: rlarltn/cosy:latest # Docker Hub의 최신 이미지 사용
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: always
